font_size 18
font_family FreeMono
bold_font auto
italic_font auto
bold_italic_font auto

symbol_map U+1F300-U+1FAFF Noto Color Emoji

background #FFFFFF
foreground #000000

#foreground #DDDDDD
#background #191919
