
Section "InputClass"
	Identifier "libinput touchpad"
	MatchDriver "libinput"
	MatchIsTouchpad "on"
	Driver "libinput"
	Option "NaturalScrolling" "true"
	Option "Tapping" "true"
	Option "AccelSpeed" "0.5"
EndSection

